AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation template to create IAM roles. (qs-1nlkhq1oj)
Resources:
  CopyLambdaDeploymentRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
        Version: '2012-10-17'
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Effect: Allow
                Resource: arn:aws:logs:*:*:*
            Version: '2012-10-17'
          PolicyName: LambdaLogging
        - PolicyDocument:
            Statement:
              - Action:
                  - s3:PutObject
                  - s3:DeleteObject
                Effect: Allow
                Resource: '*'
            Version: '2012-10-17'
          PolicyName: PutDeleteRegionalLambdaBucket
        - PolicyDocument:
            Statement:
              - Action:
                  - s3:ListBucket
                  - s3:GetObject
                Effect: Allow
                Resource: '*'
            Version: '2012-10-17'
          PolicyName: ListGetQSSBucket
    Type: AWS::IAM::Role
Outputs:
  LambdaRoleARN:
    Description: ARN of LambdaRole
    Value: !GetAtt 'LambdaRole.Arn'
  CopyLambdaDeploymentRoleARN:
    Description: ARN of CopyLambdaDeploymentRole
    Value: !GetAtt 'CopyLambdaDeploymentRole.Arn'